---
- hosts: web
  become: true
  user: test
  
    
  tasks:
    - name: install java
      yum: 
        name: java
        state: latest
    - name: installing wget
      yum:
        name: wget
        state: present
    
    - name: install apache
      yum: 
        name: httpd
        state: latest
