---
- hosts: localhost
  become: true
  connection: local
  gather_facts: False
  vars:
      instance_type: t1.micro
      security_group: Master1
      ami_id: ami-2051294a
      region: us-east-1
      keypair: XXX
      AWS_ACCESS_KEY: XXX
      AWS_SECRET_KEY: XXX


  tasks:

    - name: Provision a set of instances
      ec2:
         ec2_url: XXXX
         aws_access_key: "{{ AWS_ACCESS_KEY }}" 
         aws_secret_key: "{{ AWS_SECRET_KEY }}"
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: t2.micro
         image: "{{ ami_id }}"
         region: "{{ region }}"
         wait: true
         exact_count: 1
         count_tag:
            Name: NOde 1
         instance_tags:
            Name: NOde 1
      register: ec2
